# Generated by Django 4.2.2 on 2023-06-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf'),
        ('livros', '0002_autor_livro_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_pedido', to='clientes.cliente')),
                ('livros', models.ManyToManyField(related_name='livros_pedido', to='livros.livro')),
            ],
        ),
    ]
