# Generated by Django 4.2.2 on 2023-08-22 00:36

from django.db import migrations, models
import livros.models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=livros.models.get_upload_path_livro),
        ),
    ]
