# Generated by Django 4.2.2 on 2023-08-22 01:57

from django.db import migrations, models
import livros.models
import utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, storage=utils.storages.PrivateMediaStorage(), upload_to=livros.models.get_upload_path_livro),
        ),
    ]
