# Generated by Django 4.2.2 on 2023-06-20 00:53

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, validators=[utils.utils.valida_cpf]),
        ),
    ]
