# Generated by Django 4.2.2 on 2023-07-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_email_alter_cliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=255, null=True, blank=True)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=255, null=True, blank=True)),
                ('uf', models.CharField(max_length=2, null=True, blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
